DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS comp_events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;


CREATE TABLE IF NOT EXISTS users(
    id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(250)    NOT NULL,
    email   VARCHAR(254)    NOT NULL    UNIQUE
);

CREATE TABLE IF NOT EXISTS locations(
   id       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   lat      FLOAT       NOT NULL,
   lon      FLOAT       NOT NULL
);

CREATE TABLE IF NOT EXISTS categories(
    id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50)    NOT NULL    UNIQUE
);

CREATE TABLE IF NOT EXISTS events(
    id 					BIGINT GENERATED BY DEFAULT AS IDENTITY		NOT NULL,
	initiator_id 		BIGINT 										NOT NULL,
	category_id 		BIGINT 										NOT NULL,
	location_id 		BIGINT										NOT NULL,
	title 				VARCHAR(120) 								NOT NULL,
	annotation 			VARCHAR(2000)								NOT NULL,
	event_date 			TIMESTAMP 		WITHOUT TIME ZONE 			NOT NULL,
    paid                BOOLEAN                                     NOT NULL,
	description 		VARCHAR(7000)								NOT NULL,
	confirmed_requests  BIGINT,
	participant_limit 	BIGINT 			DEFAULT 0,
    request_moderation  BOOLEAN         DEFAULT TRUE,
	published_on 		TIMESTAMP 		WITHOUT TIME ZONE,
	created_on 			TIMESTAMP 		WITHOUT TIME ZONE,
	state 				VARCHAR(20),
	views				BIGINT,

	CONSTRAINT pk_events PRIMARY KEY (id),
	CONSTRAINT fk_initiator_id FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_location_id FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS compilations(
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title       VARCHAR(50)     NOT NULL,
        pinned      BOOLEAN         NOT NULL
);

CREATE TABLE IF NOT EXISTS comp_events(
id            		BIGINT GENERATED BY DEFAULT AS IDENTITY 	NOT NULL,
	compilation_id		BIGINT		                                NOT NULL,
	event_id        	BIGINT										NOT NULL,

	CONSTRAINT fk_compilations_events_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations (id),
	CONSTRAINT fk_compilations_events_event_id FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS requests(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id        BIGINT REFERENCES events (id) ON DELETE CASCADE,
    requester_id    BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status          VARCHAR(50)
);