version: '3.1'
services:
  stat-server:
    build: stats-service/server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
#    environment:
#      - STAT_URL_DB=jdbc:postgresql://stats-db:5432/stat
#      - STAT_USER=postgres
#      - STAT_PASSWORD=admin

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
#    ports:
#      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin


  main-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - MAIN_URL_DB=jdbc:postgresql://ewm-db:5432/ewm-db
      - MAIN_USER=postgres
      - MAIN_PASSWORD=admin
      - stats-server.url=http://stats-server:9090


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
#    ports:
#      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin